# Generated by Django 6.1 on 2026-08-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosabor',
            name='imagen_sabor',
            field=models.ImageField(blank=True, null=True, upload_to='sabores_productos/'),
        ),
    ]
